# Generated by Django 5.2.1 on 2025-06-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='embedding_id',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_id',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
